# Generated by Django 5.1.1 on 2024-10-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_no',
        ),
    ]
