# Generated by Django 5.1.1 on 2024-10-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_remove_profile_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.IntegerField(default=None),
        ),
    ]
